### ISSUE TITLE
Own home usage

### ISSUE THREAD

**Issue by mvdh02** [WillemD61/battery-planning#14]
Hello Willem,
i'm very glad with this piece op programming. And i'm using it on my home battery. I'm using te home battery with dynamic pricing. Not to sell, but to have a so low possible energy bill. Therefor is would be nice if my own everage consumption could be included in the calculation. Personly i'm not good in programming so i have no idea how to do this?

Is this that's in you're future planning?

Thanks and greetings, Martijn

**Comment by WillemD61** [comment]
Have a look [here](https://github.com/corneel27/day-ahead) for a program with more optimisation variables. Maybe that is something for you.

I am currently using my own program to run financial simulation of the past using my real energy usage and real energy production, with and without netting (saldering), for different types of contracts and with or without energy trading.

Also I am running my daily simulation (without having a real battery).

Maybe in the future I will extend, but not now. In that case I would not use average energy usage, but would use actual usage and production of the moment to determine best action.

**Comment by mvdh02** [comment]
Thanks for the reply. I will look for this program. I'm running in Domoticz so i will try to make a work around. And i agree. The real energy usage is better than average.
